image: java:7

cache:
  key: "node_modules"
  untracked: true
  paths:
  - war/node_modules/


before_script:


after_script:

stages:
  - build
  - deploy
 
build_frontend_production:
  stage: build
  environment: Production
  only:
    - configure-ci
  script:
    - cd war
    - WAR=$(pwd)
    - echo $WAR
    - npm install 
    - gulp bundle
    
build_backend_production:
  stage: build
  environment: Production
  only:
    - configure-ci
  script:
    - mvn clean install
    - cp -R ./src/META-INF ./war/WEB-INF/classes
    
 
deploy_production:
  stage: deploy
  environment: Production
  only:
    - configure-ci
  script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - cd war
    - WAR=$(pwd)
    - echo $WAR
    - appcfg.sh --enable_jar_splitting  --enable_jar_classes --noisy --service_account_json_key_file=/tmp/$CI_PIPELINE_ID.json update $WAR
