image: java:7

before_script:


after_script:
    - rm /tmp/$CI_PIPELINE_ID.json

stages:
  - build
  - test
  - deploy
 
frontend_prod_build:
  tags:
    - qdacity
  stage: build
  environment: Production
  only:
    - master
  cache:
    key: "node_modules"
    untracked: true
    paths:
    - war/node_modules/
  artifacts:
    paths:
      - war/dist/
      - war/*.jsp
    expire_in: 3 mos
  script:
    - cd war
    - echo $API_CONFIG_PRODUCTION > ./api_config.json
    - rm -f ./dist/js/*
    - npm prune
    - npm install 
    - gulp bundle
    - gulp minify
    - gulp set-react-production
    
backend_prod_build:
  tags:
    - qdacity
  stage: build
  environment: Production
  only:
    - master
  artifacts:
    paths:
      - war/WEB-INF/classes
    expire_in: 3 mos
  script:
    - mvn clean compile
    - cp -R ./src/META-INF ./war/WEB-INF/classes

backend_prod_unittest:
  tags:
    - qdacity
  stage: test
  environment: Production
  only:
    - master
  script:
    - mvn test
  dependencies:
    - backend_prod_build

deploy_prod:
  tags:
    - qdacity
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - echo $DEPLOY_KEY_FILE_PRODUCTION > /tmp/$CI_PIPELINE_ID.json
    - WAR=$(pwd)/war
    - appcfg.sh --enable_jar_splitting  --enable_jar_classes --noisy --service_account_json_key_file=/tmp/$CI_PIPELINE_ID.json update $WAR
