FROM qdacity-tests-base:latest

# Copy repository
WORKDIR /app
COPY ./target /app/target
COPY ./docker /app/docker
COPY ./war/tests/acceptance-tests /app/war/tests/acceptance-tests
COPY ./war/node_modules /app/war/node_modules
COPY ./war/gulp-plugins /app/war/gulp-plugins
COPY ./war/gulpfile.js /app/war/gulpfile.js

# Allow execute
RUN sudo chmod +x ./docker/acceptance-tests/entrypoint.sh
RUN sudo chmod +x ./docker/acceptance-tests/startTests.sh

# Run script which starts the devserver and executes the tests
ENTRYPOINT ./docker/acceptance-tests/entrypoint.sh