FROM qdacity-tests-base:latest

# Copy repository
WORKDIR /app
COPY ./docker /app/docker

# Run script which starts the devserver and executes the tests
ENTRYPOINT ./docker/acceptance-tests/entrypoint.sh